'use strict';
const $=id=>document.getElementById(id), esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c])),money=v=>new Intl.NumberFormat('en-US',{style:'currency',currency:'USD'}).format(v);
const catalog=[
{id:'BTC',name:'Bitcoin',price:50000,about:'A digital asset transferred through a shared network rather than a bank. Its design limits the total supply.',risk:'Its price can fall sharply. Limited supply does not guarantee demand or a rising price.'},
{id:'ETH',name:'Ethereum',price:2500,about:'A blockchain used to run applications and agreements in code. Ether is its native asset and is used to pay network fees.',risk:'Applications can have bugs, and network activity does not guarantee a higher Ether price.'},
{id:'SOL',name:'Solana',price:100,about:'A blockchain designed for applications and fast transactions. SOL is its native asset.',risk:'Network reliability, competition and changing demand can affect it.'},
{id:'ADA',name:'Cardano',price:0.5,about:'A blockchain platform whose native asset is ADA.',risk:'Adoption and competition matter. A small price per coin does not mean it is cheap.'},
{id:'LINK',name:'Chainlink',price:15,about:'A network designed to connect blockchain applications with outside data. LINK is its token.',risk:'Use of a service and the value captured by its token are different questions.'},
{id:'DOGE',name:'Dogecoin',price:0.1,about:'A cryptocurrency associated with an online community and internet culture.',risk:'Sentiment can change quickly. Popularity is not a reliable valuation method.'},
{id:'AVAX',name:'Avalanche',price:25,about:'A blockchain ecosystem for applications and custom networks. AVAX is its native asset.',risk:'Competition, token supply and actual adoption can affect its price.'},
{id:'XRP',name:'XRP',price:0.6,about:'The native asset of the XRP Ledger, a network used to transfer value.',risk:'Understand the token’s role, supply and legal context before making real decisions.'}
];
const key='crypto-learning-lab-v1';
const fresh=()=>({coins:catalog.slice(0,2),cash:1000,contributed:1000,fees:0,holdings:{},trades:[],entries:[]});
let state;try{state=JSON.parse(localStorage.getItem(key))||fresh();if(!Array.isArray(state.coins)||!Number.isFinite(state.cash)||!Array.isArray(state.entries)||!Array.isArray(state.trades)||!state.holdings)state=fresh()}catch{state=fresh()}
let toastTimer;
function toast(msg){$('toast').textContent=msg;$('toast').style.display='block';clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('toast').style.display='none',4500)}
function save(){try{localStorage.setItem(key,JSON.stringify(state))}catch{toast('Browser storage is unavailable. Download your progress before leaving.')}render()}
function tab(id){document.querySelectorAll('.panel').forEach(p=>p.hidden=p.id!==id);document.querySelectorAll('nav button').forEach(b=>b.setAttribute('aria-selected',String(b.dataset.tab===id)))}
document.querySelectorAll('nav button').forEach(b=>b.onclick=()=>tab(b.dataset.tab));
function addCoin(coin){if(!coin||!coin.id||!Number.isFinite(coin.price)||coin.price<=0)throw Error('Choose a valid coin.');if(state.coins.some(c=>c.id.toUpperCase()===coin.id.toUpperCase()))throw Error('This coin is already on your watchlist.');state.coins.push({...coin});save();renderCatalog();toast(coin.name+' added.');return {symbol:coin.id,watchlistSize:state.coins.length}}
function renderCatalog(){let query=$('search').value.toLowerCase();let list=catalog.filter(c=>(c.name+' '+c.id).toLowerCase().includes(query));$('catalog').innerHTML=list.length?list.map(c=>`<div class="catalogRow"><div><strong>${esc(c.name)}</strong><small>${c.id}</small></div><button data-add="${c.id}" ${state.coins.some(x=>x.id===c.id)?'disabled':''}>${state.coins.some(x=>x.id===c.id)?'Added':'Add'}</button></div>`).join(''):'<p>No match. You can add a different crypto below.</p>';$('catalog').querySelectorAll('[data-add]').forEach(b=>b.onclick=()=>{try{addCoin(catalog.find(c=>c.id===b.dataset.add))}catch(e){toast(e.message)}})}
function openAdd(){renderCatalog();$('addDialog').showModal()}
$('addTop').onclick=openAdd;$('search').oninput=renderCatalog;document.querySelectorAll('[data-close]').forEach(b=>b.onclick=()=>$(b.dataset.close).close());
$('customForm').onsubmit=e=>{e.preventDefault();const name=$('customName').value.trim(),id=$('customSymbol').value.trim().toUpperCase();if(!name||!/^[A-Z0-9-]{1,12}$/.test(id)){toast('Enter a name and a ticker of up to 12 letters or numbers.');return}try{addCoin({id,name,price:10,custom:true,about:'You added this coin. Its purpose has not been verified in this app.',risk:'Research its network, token supply, liquidity and security. This app has no verified research for this coin.'});e.target.reset()}catch(err){toast(err.message)}};
function detail(id){const c=state.coins.find(c=>c.id===id);if(!c)return;$('detailTitle').textContent=c.name+' ('+c.id+')';$('detailBody').innerHTML=`<p class="eyebrow">${c.custom?'CUSTOM COIN':'COIN BASICS'}</p><h3>What is it?</h3><p>${esc(c.about)}</p><h3>What could go wrong?</h3><p>${esc(c.risk)}</p><h3>Your research checklist</h3><p>What problem does it solve? Who uses it? How is new supply created? Can you sell without a large price impact? Which sources support your understanding?</p><div class="notice"><span>Example price: ${money(c.price)}. This price is invented for learning and stays fixed in the practice account.</span></div><button id="tryCoin" class="primary">Practice with this coin</button>`;$('detailDialog').showModal();$('tryCoin').onclick=()=>{$('detailDialog').close();tab('practice');$('tradeCoin').value=id;$('tradeAmount').focus()}}
function removeCoin(id){if((state.holdings[id]||0)>1e-10){toast('Sell your practice holding before removing this coin.');return}state.coins=state.coins.filter(c=>c.id!==id);save();toast('Coin removed from your watchlist.')}
function recordTrade(id,action,amount){const c=state.coins.find(c=>c.id===id);if(!c||!['buy','sell'].includes(action)||!Number.isFinite(amount)||amount<1||amount>1000000)throw Error('Choose a coin and enter an amount between $1 and $1,000,000.');const fee=amount*.005,units=amount/c.price;if(action==='buy'){if(amount+fee>state.cash+1e-8)throw Error('You need enough practice cash to cover the purchase and fee.');state.cash-=amount+fee;state.holdings[id]=(state.holdings[id]||0)+units}else{if(units>(state.holdings[id]||0)+1e-10)throw Error('The sale exceeds your practice holding.');state.holdings[id]=Math.max(0,state.holdings[id]-units);state.cash+=amount-fee}state.fees+=fee;const t={id:crypto.randomUUID(),symbol:id,action,amount,units,price:c.price,fee,at:new Date().toISOString()};state.trades.unshift(t);save();toast('Practice '+action+' recorded. Fee: '+money(fee));return {action,symbol:id,amount,fee,cash:state.cash}}
$('tradeForm').onsubmit=e=>{e.preventDefault();try{recordTrade($('tradeCoin').value,$('tradeAction').value,Number($('tradeAmount').value))}catch(err){toast(err.message)}};
$('depositForm').onsubmit=e=>{e.preventDefault();let n=Number($('deposit').value);if(!Number.isFinite(n)||n<1||n>1000000){toast('Enter a deposit from $1 to $1,000,000.');return}state.cash+=n;state.contributed+=n;save();toast('Fictional cash added.')};
function render(){let selected=$('tradeCoin').value;$('coinCount').textContent=state.coins.length+' coins';$('coins').innerHTML=state.coins.map(c=>`<article class="coin"><div class="coinHeader"><span class="coinIcon" aria-hidden="true">${esc(c.id.slice(0,1))}</span><div><h3 style="margin:0">${esc(c.name)}</h3><span class="ticker">${esc(c.id)}${c.custom?' · Custom':''}</span></div></div><div class="price">${money(c.price)}</div><p class="muted">Invented example price</p><p>${esc(c.about)}</p><div class="actions"><button data-detail="${esc(c.id)}">Explore & learn</button><button class="remove" data-remove="${esc(c.id)}" aria-label="Remove ${esc(c.name)}">Remove</button></div></article>`).join('')+'<button class="addCard" id="addCard">+ Add another crypto<span>Build your own learning watchlist</span></button>';$('addCard').onclick=openAdd;$('coins').querySelectorAll('[data-detail]').forEach(b=>b.onclick=()=>detail(b.dataset.detail));$('coins').querySelectorAll('[data-remove]').forEach(b=>b.onclick=()=>removeCoin(b.dataset.remove));$('tradeCoin').innerHTML=state.coins.map(c=>`<option value="${esc(c.id)}">${esc(c.name)} (${esc(c.id)})</option>`).join('');if(state.coins.some(c=>c.id===selected))$('tradeCoin').value=selected;
let holdingValue=state.coins.reduce((sum,c)=>sum+(state.holdings[c.id]||0)*c.price,0),equity=state.cash+holdingValue;$('accountStats').innerHTML=[['Practice account value',equity],['Available cash',state.cash],['Fictional cash added',state.contributed],['Gain / loss after fees',equity-state.contributed]].map(([label,v])=>`<div class="stat"><span>${label}</span><strong>${money(v)}</strong></div>`).join('');let held=state.coins.filter(c=>(state.holdings[c.id]||0)>1e-10);$('holdings').innerHTML=held.length?held.map(c=>`<div class="row"><div><strong>${esc(c.name)}</strong><br>${(state.holdings[c.id]).toLocaleString('en-US',{maximumFractionDigits:8})} ${esc(c.id)}</div><strong>${money(state.holdings[c.id]*c.price)}</strong></div>`).join(''):'<p>No holdings yet. Try a small fictional purchase to learn about fractional coins and fees.</p>';$('history').innerHTML=state.trades.length?state.trades.slice(0,20).map(t=>`<div class="row"><div><strong>${t.action==='buy'?'Bought':'Sold'} ${esc(t.symbol)}</strong><br>${new Date(t.at).toLocaleDateString()} · fee ${money(t.fee)}</div><span>${money(t.amount)}</span></div>`).join(''):'<p>No trades yet.</p>';
$('entries').innerHTML=state.entries.map(e=>`<div class="entry"><time>${new Date(e.at).toLocaleDateString()}</time><p><strong>Expected:</strong> ${esc(e.expectation)}</p><p><strong>Learned:</strong> ${esc(e.reflection)}</p><button data-delete="${e.id}">Delete reflection</button></div>`).join('');$('entries').querySelectorAll('[data-delete]').forEach(b=>b.onclick=()=>{if(confirm('Delete this reflection?')){state.entries=state.entries.filter(e=>e.id!==b.dataset.delete);save()}})}
const lessons=[['Crypto & blockchain','A blockchain is a shared transaction record maintained by a network. A cryptocurrency is a digital asset associated with such a network. Different assets have different purposes; they are not shares in a company.'],['Spot trading','Buying spot crypto means buying the asset itself. This app practices purchases without borrowing. You can buy a fraction of a coin rather than an entire coin.'],['Volatility','Volatility describes how much prices move. Bigger movements create both opportunities and losses. A coin that rises 20% can also fall 20% or more.'],['Trend & pullback','A trend is a sustained direction in price. A pullback is a decline within a broader rise. You only know for certain whether it was a pullback after seeing what followed.'],['Breakout','A breakout occurs when a price moves beyond a previous range. Some breakouts continue; others reverse. A rule needs testing rather than confidence from a single chart.'],['Fees & spread','A fee is a charge for trading. The spread is the gap between buying and selling prices. Slippage is the difference between your expected and actual execution price. All can reduce results.'],['Stop loss & drawdown','A stop loss is an instruction or plan to exit after a decline. It does not guarantee a specific loss. Drawdown is a fall from an account’s previous peak.'],['Coin price & supply','A $0.10 coin is not automatically cheaper than a $50,000 coin. Consider how many units exist, how new units enter circulation, and what demand supports them.'],['Security & custody','Custody describes who controls access to the assets. Learn how wallets, private keys and exchange accounts differ. Never share private keys or recovery phrases.']];$('lessons').innerHTML=lessons.map(([title,body])=>`<details><summary>${title}</summary><p>${body}</p></details>`).join('');
$('journalForm').onsubmit=e=>{e.preventDefault();const expectation=$('expectation').value.trim(),reflection=$('reflection').value.trim();if(!expectation||!reflection){toast('Complete both reflection fields.');return}state.entries.unshift({id:crypto.randomUUID(),expectation,reflection,at:new Date().toISOString()});save();e.target.reset();toast('Reflection saved.')};
const paths={rise:[100,104,110,102,115,123,118,133,140,128,150,160,168],fall:[100,96,88,92,80,75,82,70,65,72,60,55,58],chop:[100,112,98,108,92,105,99,115,94,109,102,96,103]};
function simulate(prices,initial,monthly,fee,kind){let cash=initial,units=0,entry=0,trades=0,fees=0,peak=initial,dd=0,curve=[],signal='';const buy=p=>{if(cash<=0)return;let spend=cash/(1+fee);units+=spend/p;entry=p;fees+=spend*fee;cash=0;trades++},sell=p=>{if(units<=0)return;fees+=units*p*fee;cash+=units*p*(1-fee);units=0;trades++};if(kind==='hold'||kind==='regular')buy(prices[0]);curve.push(cash+units*prices[0]);for(let i=1;i<prices.length;i++){cash+=monthly;peak+=monthly;const p=prices[i];if(kind==='regular')buy(p);if(signal==='buy')buy(p);if(signal==='sell')sell(p);signal='';let value=cash+units*p;peak=Math.max(peak,value);dd=Math.min(dd,(value-peak)/peak);curve.push(value);if(kind==='pullback'){if(units===0&&p/prices[i-1]-1<=-.05)signal='buy';else if(units>0&&p/entry-1>=.1)signal='sell'}if(kind==='breakout'){if(units===0&&i>=3&&p>Math.max(...prices.slice(i-3,i)))signal='buy';else if(units>0&&p/entry-1<=-.08)signal='sell'}}return {curve,value:curve.at(-1),trades,fees,dd}}
function compare(){let initial=Number($('initial').value),monthly=Number($('monthly').value),fee=Number($('fee').value)/100;if(!Number.isFinite(initial)||initial<10||initial>1000000||!Number.isFinite(monthly)||monthly<0||monthly>100000||!Number.isFinite(fee)||fee<0||fee>.05){toast('Use a starting balance from $10 to $1,000,000, contributions from $0 to $100,000, and fees from 0% to 5%.');return}const specs=[['hold','Buy & hold','#153f4a'],['regular','Regular buying','#238d79'],['pullback','Pullback','#b66b22'],['breakout','Breakout','#7755b1']];let results=specs.map(([id,name,color])=>({...simulate(paths[$('scenario').value],initial,monthly,fee,id),name,color}));const contributed=initial+monthly*12;$('comparison').innerHTML=`<p>Total fictional cash added: <strong>${money(contributed)}</strong>. Results include cash and holdings valued at the final example price; no final sale is assumed.</p><div class="resultGrid">`+results.map(r=>`<article class="result" style="border-top:3px solid ${r.color}"><h3>${r.name}</h3><strong>${money(r.value)}</strong><p>Gain / loss: ${money(r.value-contributed)}<br>Fees paid: ${money(r.fees)}<br>Trades: ${r.trades}<br>Drawdown*: ${(r.dd*100).toFixed(1)}%</p></article>`).join('')+'</div><p class="muted">*Drawdown adjusts the running peak for contributions. This simplified lesson does not estimate future performance.</p>';
let vals=results.flatMap(r=>r.curve),min=Math.min(...vals)*.9,max=Math.max(...vals)*1.05,y=v=>190-(v-min)/(max-min)*165;$('chart').innerHTML=`<p class="muted">Fictional account value over 12 months · range ${money(min)}–${money(max)}</p><svg viewBox="0 0 800 220" role="img" aria-label="Illustrative account value comparison across twelve months">${[0,1,2].map(i=>`<line x1="20" y1="${25+i*80}" x2="780" y2="${25+i*80}" stroke="#e2e9ef"/>`).join('')}${results.map(r=>`<polyline points="${r.curve.map((v,i)=>(20+i*63)+','+y(v)).join(' ')}" fill="none" stroke="${r.color}" stroke-width="3"/>`).join('')}<text x="20" y="215" fill="#52677b" font-size="14">Start</text><text x="700" y="215" fill="#52677b" font-size="14">Month 12</text></svg><div class="legend">${results.map(r=>`<span style="color:${r.color}">━ ${r.name}</span>`).join('')}</div>`}
$('runComparison').onclick=compare;
$('export').onclick=()=>{const url=URL.createObjectURL(new Blob([JSON.stringify({exportedAt:new Date().toISOString(),mode:'fictional learning only',...state},null,2)],{type:'application/json'}));const a=document.createElement('a');a.href=url;a.download='crypto-learning-progress.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)};
$('reset').onclick=()=>{if(confirm('Reset your watchlist, practice trades and journal in this browser? Download your progress first if you want a copy.')){state=fresh();save();toast('Practice data reset.')}};
if(document.modelContext?.registerTool){for(const tool of [{name:'add_watchlist_crypto',title:'Add crypto to watchlist',description:'Add a supported crypto to the personal learning watchlist. Does not buy it.',inputSchema:{type:'object',properties:{symbol:{type:'string'}},required:['symbol'],additionalProperties:false},annotations:{readOnlyHint:false},execute(input){if(typeof input?.symbol!=='string')throw Error('A symbol is required.');const c=catalog.find(c=>c.id===input.symbol.toUpperCase());if(!c)throw Error('Unsupported catalog symbol. Use the custom coin form.');return addCoin(c)}},{name:'read_learning_account',title:'Read practice account',description:'Read the fictional practice account and watchlist; all prices are teaching examples.',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:true},execute(){return {mode:'fictional',cash:state.cash,contributed:state.contributed,fees:state.fees,coins:state.coins.map(c=>({symbol:c.id,name:c.name,examplePrice:c.price})),holdings:{...state.holdings}}}}]){try{Promise.resolve(document.modelContext.registerTool(tool)).catch(()=>{})}catch{}}}
render();compare();
